//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class cars
    {
        public int ID { get; set; }
        public string Name_car { get; set; }
        public int ID_Defect { get; set; }
    
        public virtual defects defects { get; set; }
        public object carName { get; internal set; }
        public object defectID { get; internal set; }
    }
}
