//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class parts_player
    {
        public int ID_part { get; set; }
        public int count { get; set; }
        public int ID_player { get; set; }
    
        public virtual parts parts { get; set; }
        public virtual player player { get; set; }
    }
}
